default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: wingman_development

test:
  <<: *default
  database: wingman_test

production:
  <<: *default
  database: wingman_production
  username: wingman
  password: <%= ENV['WINGMAN_DATABASE_PASSWORD'] %>